import type {BreadTranslation} from '../types/bread'

export const BREAD_TRANSLATIONS: BreadTranslation[] = [
  {
    id: 'en',
    label: '🇺🇸 EN',
    title: 'Bread - Espen.Codes',
    heading: 'Baking Bread',
    intro:
      "Bread is really nice. But the ones you find in the United States tend to be very loafy. I prefer ones that are denser, crispier, where the texture isn't just air and flour, but rather actual seeds and grains.",
    figcaption1: 'A home baked loaf of bread. You should try it!',
    paragraph1:
      "I started baking this bread pictured above. It's not super fancy. There is no sourdough to keep alive. There is no kneading. There is really very little work involved.",
    paragraph2:
      "You might have to go shopping for a bunch of seeds for the first batch here, but once purchased you can make quite a lot of these. I'll calculate the price per bread at some point!",
    statsHeading: 'Stats',
    activeTime: 'Active time spent: ~15 minutes',
    totalTime: 'Time from start to finish: ~3 hours',
    ingredientsHeading: 'Ingredients',
    servings: '(makes 1 smallish loaf)',
    ingredients: [
      '175g whole wheat flour',
      '125g all purpose flour',
      '20g oats',
      '20g sunflower kernels',
      '35g flax seed',
      '25g pumpkin seeds',
      '20g chia seeds',
      '0.5 tbsp salt',
      '1 tbsp honey (can be dropped)',
      '1 packet of dry yeast (~7g)',
      '333 ml water (approx body temperature)',
      'Optional: some dry berries or whatever you might want for extra flavor',
    ],
    instructionsHeading: 'Instructions',
    instructions: [
      'Measure out and throw everything in a bowl.',
      "Mix everything together. I like to use a silicone spatula for this. The dough shouldn't be dry, but it shouldn't be wet either.",
      'Cover the bowl lightly and leave it for at least 1 hour.',
      'Oil the sides and bottom of a loaf pan.',
      "Pour or scoop the dough into the oiled pan. It'll look like it's far from enough, but the yeast will do its thing.",
      'Leave for 1 hour, lightly wrapped.',
      'Preheat the oven to 225°C / 437°F.',
      'Put the pan into the oven and bake for 40 minutes.',
      'Remove the bread and drop it out of the pan.',
      'For a crisp crust, flip it upside down into the pan and bake for another ~10 minutes.',
    ],
    figcaption2:
      'Two slices of home baked bread with brown goat cheese, sour cream and blueberry jam.',
  },
  {
    id: 'no',
    label: '🇳🇴 NO',
    title: 'Brød - Espen.Codes',
    heading: 'Brødbaking',
    intro:
      'Brød er digg. Men de man finner i USA pleier å være veldig… luftige? Bare tomme kalorier? Jeg foretrekker brød som er mer kompakt, sprøere, hvor teksturen ikke bare er luft og mel, men faktisk frø og korn.',
    figcaption1: 'Et hjemmebakt brød. Du bør prøve det!',
    paragraph1:
      'Da jeg flyttet hit begynte jeg å bake brødet som er avbildet over. Det er ikke super fancy. Det er ingen surdeig å holde i live. Ingen elting. Det er faktisk veldig lite arbeid involvert.',
    paragraph2:
      'Du må kanskje handle en masse frø den første gangen du baker det, men når du først har kjøpt det kan du lage ganske mange av disse.',
    statsHeading: 'Statistikk',
    activeTime: 'Aktiv tid brukt: ~15 minutter',
    totalTime: 'Tid fra start til slutt: ~3 timer',
    ingredientsHeading: 'Ingredienser',
    servings: '(1 lite brød)',
    ingredients: [
      '175g sammalt hvetemel',
      '125g siktet hvetemel',
      '20g havregryn',
      '20g solsikkekjerner',
      '35g linfrø',
      '25g gresskarkjerner',
      '20g chiafrø',
      '0.5 ss salt',
      '1 ss honning (kan droppes)',
      '1 pakke tørrgjær (~7g)',
      '333 ml vann (omtrent kroppstemperatur)',
      'Valgfritt: noen tørkede bær eller andre ting du måtte ønske for ekstra smak',
    ],
    instructionsHeading: 'Instruksjoner',
    instructions: [
      'Mål opp og kast alt i en bolle.',
      'Bland alt sammen. Deigen skal ikke være tørr, men den skal heller ikke være våt.',
      'Dekk bollen lett og la den stå i minst 1 time.',
      'Olje sidene og bunnen av en brødform.',
      'Hell eller dytt deigen over i formen. Gjæren vil gjøre jobben sin.',
      'La stå i 1 time, lett innpakket.',
      'Forvarm ovnen til 225°C.',
      'Sett formen i ovnen og stek i 40 minutter.',
      'Ta ut brødet og slipp det ut av formen.',
      'For sprø skorpe, vend det opp ned i formen og stek i ytterligere ~10 minutter.',
    ],
    figcaption2: 'To skiver hjemmebakt brød med ekte geitost, rømme og blåbærsyltetøy.',
  },
]
